-d D:\document\GitHub\PE_module\asl_soc\asl_soc\impl\gwsynthesis\asl_soc.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst D:\document\GitHub\PE_module\asl_soc\asl_soc\src\asl_soc.cst
-cfg D:\document\GitHub\PE_module\asl_soc\asl_soc\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
