-d D:\document\GitHub\PE_module\IRCAM\impl\gwsynthesis\TEST.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst D:\document\GitHub\PE_module\IRCAM\src\TEST.cst
-cfg D:\document\GitHub\PE_module\IRCAM\impl\pnr\device.cfg
-sdc D:\document\GitHub\PE_module\IRCAM\src\TEST.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
