-d D:\OneDrive\UoG_challenge_course\TEST\impl\gwsynthesis\TEST.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst D:\OneDrive\UoG_challenge_course\TEST\src\TEST.cst
-cfg D:\OneDrive\UoG_challenge_course\TEST\impl\pnr\device.cfg
-sdc D:\OneDrive\UoG_challenge_course\TEST\src\TEST.sdc
-gao_crc 0011110000000001
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-correct_hold 1
-route_maxfan 23
-rtl_gao
